cc_library(
  name = "sim",
  srcs = glob(["*.cc"]),
  hdrs = glob(["*.h"]),
  deps = ["//apps/libmc:constants",
          "@com_google_protobuf//:protobuf_lite"],
  visibility = ["//apps/libmc:__subpackages__"],
)
