cc_library(
  name = "graphics",
  srcs = glob(["*.cc"]),
  hdrs = glob(["*.h"]),
  deps = ["//apps/libmc/graphics/internal",
          "//apps/libmc/graphics/types"],
  visibility = ["//apps/libmc:__subpackages__"],
)
