py_library(
  name = "virtual_cube",
  srcs = glob(["*.py"]),
  data = glob(["assets/*"]),
  deps = ["//apps/libmc/sim/protobuf:python_system_action"],
  visibility = ["//simulator/virtual_cube/tests:__pkg__"],
)
