py_test(
  name = "test_cube",
  srcs = ["test_cube.py"],
  deps = ["//simulator",
          "//simulator/virtual_cube",
          "//apps/libmc/sim/protobuf:python_graphics_message"],
  size = "small",
)

py_test(
  name = "test_event_generator",
  srcs = ["test_event_generator.py"],
  deps = ["//simulator"],
  size = "small",
)

py_test(
  name = "test_tabletop",
  srcs = ["test_tabletop.py"],
  deps = ["//simulator"],
  size = "small",
)

py_test(
  name = "test_cube_event_handler",
  srcs = ["test_cube_event_handler.py"],
  deps = ["//simulator"],
  size = "small",
)

py_test(
  name = "test_obj_canvas",
  srcs = ["test_obj_canvas.py"],
  deps = ["//simulator"],
  size = "small",
)

py_test(
  name = "test_display",
  srcs = ["test_display.py"],
  deps = ["//simulator"],
  size = "small",
)
