py_test(
  name = "test_cube",
  srcs = ["test_cube.py"],
  deps = ["//simulator"],
  size = "small",
)

py_test(
  name = "test_event_generator",
  srcs = ["test_event_generator.py"],
  deps = ["//simulator"],
  size = "small",
)

py_test(
  name = "test_tabletop",
  srcs = ["test_tabletop.py"],
  deps = ["//simulator"],
  size = "small",
)

py_test(
  name = "test_cube_event_handler",
  srcs = ["test_cube_event_handler.py"],
  deps = ["//simulator"],
  size = "small",
)
